spring:
  profiles:
    active: zhou
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.89.212:3306/securitydb
    username: security
    password: Xplusplus-root-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  context-path: /security
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-alias: tomcat
#    key-store-password: 123456
  port: 9000
